fixed cypress, blue green deployment and testing the pipeline

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -210,22 +210,16 @@ jobs:
           currentSlot=`(helm get values --all ${{env.APP_NAME_SHORT}} | grep -Po 'productionSlot: \K.*')`
           echo $currentSlot
           if [ "$currentSlot" == "blue" ]; then
-              oldSlot="blue"
-              newSlot="green"
-              deploymentOption=$newSlot.enabled=true
-              echo $deploymentOption
-              echo "oldSlot=$oldSlot" >> $GITHUB_ENV
-              echo "newSlot=$newSlot" >> $GITHUB_ENV
-              helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_green=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_green=1.${{ github.run_number }} --reuse-values
+            oldSlot="blue"
+            newSlot="green"
           else
-              oldSlot="green"
-              newSlot="blue"
-              deploymentOption=$newSlot.enabled=true
-              echo $deploymentOption
-              echo "oldSlot=$oldSlot" >> $GITHUB_ENV
-              echo "newSlot=$newSlot" >> $GITHUB_ENV
-              helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_blue=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_blue=1.${{ github.run_number }} --reuse-values
+            oldSlot="green"
+            newSlot="blue"
           fi
+
+          echo "oldSlot=$oldSlot" >> $GITHUB_ENV
+          echo "newSlot=$newSlot" >> $GITHUB_ENV
+          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
 
       - name: Manual aprroval
         uses: trstringer/manual-approval@v1
@@ -244,7 +238,39 @@ jobs:
         run: |
           deploymentOption=productionSlot=$newSlot
           echo $deploymentOption
-          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set $deploymentOption --reuse-values
+
+          # Deploy the new version (either blue or green) and wait for it to become ready
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --reuse-values
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} --timeout=60s; then
+            echo "Deployment failed. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
+
+          # Swap selectors to direct production traffic to the new version (newSlot)
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set "$deploymentOption" --reuse-values
+
+          # Allow some time for Kubernetes to apply the Service update
+          sleep 5
+
+          # Fetch the current selector for the production service and compare it to the desired state
+          CURRENT_SELECTOR=$(kubectl get svc "${{env.APP_NAME_SHORT}}-prod" -n ${{env.NAMESPACE}} -o=jsonpath='{.spec.selector.slot}')
+
+          if [[ "$CURRENT_SELECTOR" == *"${newSlot}"* ]]; then
+            echo "Service selector updated successfully."
+          else
+            echo "Service selector not updated. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
+
+          # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${newSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} --timeout=60s; then
+            echo "Deployment failed. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
 
       # - name: Cleanup Old slot
       #   run: |
diff --git a/.github/workflows/customers-service-ci-cd.yaml b/.github/workflows/customers-service-ci-cd.yaml
--- a/.github/workflows/customers-service-ci-cd.yaml
+++ b/.github/workflows/customers-service-ci-cd.yaml
@@ -21,84 +21,84 @@ env:
   NAMESPACE: spring-petclinic
 
 jobs:
-  # setup:
-  #   runs-on: ubuntu-latest
-  #   steps:
-  #     - name: Check out repository code
-  #       uses: actions/checkout@v4
+  setup:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
 
-  #     - name: Set up Java 11
-  #       uses: actions/setup-java@v4
-  #       with:
-  #         distribution: "adopt" # See 'Supported distributions' for available options
-  #         java-version: "11"
-  #         cache: "maven"
-  #         cache-dependency-path: "${{env.APP_PATH}}/pom.xml"
+      - name: Set up Java 11
+        uses: actions/setup-java@v4
+        with:
+          distribution: "adopt" # See 'Supported distributions' for available options
+          java-version: "11"
+          cache: "maven"
+          cache-dependency-path: "${{env.APP_PATH}}/pom.xml"
 
-  # integration_tests:
-  #   runs-on: ubuntu-latest
-  #   needs: setup
-  #   steps:
-  #     - name: Check out repository code
-  #       uses: actions/checkout@v4
+  integration_tests:
+    runs-on: ubuntu-latest
+    needs: setup
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
 
-  #     - name: Set up Java 11
-  #       uses: actions/setup-java@v4
-  #       with:
-  #         distribution: "adopt" # See 'Supported distributions' for available options
-  #         java-version: "11"
-  #         cache: "maven"
-  #         cache-dependency-path: "${{env.APP_PATH}}/pom.xml"
+      - name: Set up Java 11
+        uses: actions/setup-java@v4
+        with:
+          distribution: "adopt" # See 'Supported distributions' for available options
+          java-version: "11"
+          cache: "maven"
+          cache-dependency-path: "${{env.APP_PATH}}/pom.xml"
 
-  #     - name: Run tests
-  #       run: cd ${{env.APP_PATH}} && mvn test
+      - name: Run tests
+        run: cd ${{env.APP_PATH}} && mvn test
 
-  # code_quality_and_security_scanning:
-  #   runs-on: ubuntu-latest
-  #   needs: integration_tests
-  #   steps:
-  #     - name: Check out repository code
-  #       uses: actions/checkout@v4
+  code_quality_and_security_scanning:
+    runs-on: ubuntu-latest
+    needs: integration_tests
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
 
-  #     - name: Set up Java 17
-  #       uses: actions/setup-java@v4
-  #       with:
-  #         distribution: "adopt"
-  #         java-version: "17"
+      - name: Set up Java 17
+        uses: actions/setup-java@v4
+        with:
+          distribution: "adopt"
+          java-version: "17"
 
-  #     - name: Run OWASP Dependency Check
-  #       run: |
-  #         # Download and unzip Dependency-Check
-  #         wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
-  #         unzip dependency-check-9.0.9-release.zip
+      - name: Run OWASP Dependency Check
+        run: |
+          # Download and unzip Dependency-Check
+          wget https://github.com/jeremylong/DependencyCheck/releases/download/v9.0.9/dependency-check-9.0.9-release.zip
+          unzip dependency-check-9.0.9-release.zip
 
-  #         # Run Dependency-Check
-  #         ./dependency-check/bin/dependency-check.sh --project "${{env.APP_NAME}}" --scan "${{env.APP_PATH}}" --nvdApiKey "${{ secrets.NVD_API_KEY }}" --format "HTML" --out "${{env.APP_PATH}}/reports"
+          # Run Dependency-Check
+          ./dependency-check/bin/dependency-check.sh --project "${{env.APP_NAME}}" --scan "${{env.APP_PATH}}" --nvdApiKey "${{ secrets.NVD_API_KEY }}" --format "HTML" --out "${{env.APP_PATH}}/reports"
 
-  #     - name: Upload Dependency Check Report
-  #       uses: actions/upload-artifact@v2
-  #       with:
-  #         name: dependency-check-report
-  #         path: ${{env.APP_PATH}}/reports/dependency-check-report.html
+      - name: Upload Dependency Check Report
+        uses: actions/upload-artifact@v2
+        with:
+          name: dependency-check-report
+          path: ${{env.APP_PATH}}/reports/dependency-check-report.html
 
-  #     - name: Run SonarCloud analysis
-  #       env:
-  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-  #         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CUSTOMERS_SERVICE }}
-  #       run: |
-  #         cd ${{env.APP_PATH}} && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
-  #         -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}} \
-  #         -Dsonar.organization=jaro233 \
-  #         -Dsonar.host.url=https://sonarcloud.io \
-  #         -Dsonar.login=${{ env.SONAR_TOKEN }} \
-  #         -Dsonar.qualitygate.wait=true \
-  #         -Dsonar.dependencyCheck.reportPath=.${{env.APP_PATH}}/reports/dependency-check-report.html
+      - name: Run SonarCloud analysis
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CUSTOMERS_SERVICE }}
+        run: |
+          cd ${{env.APP_PATH}} && mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
+          -Dsonar.projectKey=${{env.SONAR_PROJECT_KEY}} \
+          -Dsonar.organization=jaro233 \
+          -Dsonar.host.url=https://sonarcloud.io \
+          -Dsonar.login=${{ env.SONAR_TOKEN }} \
+          -Dsonar.qualitygate.wait=true \
+          -Dsonar.dependencyCheck.reportPath=.${{env.APP_PATH}}/reports/dependency-check-report.html
 
   build_and_push:
     runs-on: ubuntu-latest
     outputs:
       ecr-registry: ${{ steps.login-ecr-private.outputs.registry }}
-    # needs: code_quality_and_security_scanning
+    needs: code_quality_and_security_scanning
     steps:
       - name: Check out repository code
         uses: actions/checkout@v4
@@ -139,40 +139,40 @@ jobs:
           tags: ${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}}:1.${{ github.run_number }}
           push: true
 
-  # docker_image_scanning:
-  #   runs-on: ubuntu-latest
-  #   needs: build_and_push
-  #   steps:
-  #     - name: Check out repository code
-  #       uses: actions/checkout@v4
+  docker_image_scanning:
+    runs-on: ubuntu-latest
+    needs: build_and_push
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
 
-  #     - name: Configure AWS Credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ secrets.AWS_REGION }}
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
 
-  #     - name: Login to Amazon ECR Private
-  #       id: login-ecr-private
-  #       uses: aws-actions/amazon-ecr-login@v2
-  #       with:
-  #         registry-type: private
+      - name: Login to Amazon ECR Private
+        id: login-ecr-private
+        uses: aws-actions/amazon-ecr-login@v2
+        with:
+          registry-type: private
 
-  #     - name: Scan the Docker image with Trivy
-  #       uses: aquasecurity/trivy-action@master
-  #       with:
-  #         image-ref: ${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}}:1.${{ github.run_number }}
-  #         format: "table"
-  #         exit-code: "0"
-  #         ignore-unfixed: true
-  #         vuln-type: "os,library"
-  #         severity: "CRITICAL,HIGH"
+      - name: Scan the Docker image with Trivy
+        uses: aquasecurity/trivy-action@master
+        with:
+          image-ref: ${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}}:1.${{ github.run_number }}
+          format: "table"
+          exit-code: "0"
+          ignore-unfixed: true
+          vuln-type: "os,library"
+          severity: "CRITICAL,HIGH"
 
   deployment:
     runs-on: ubuntu-latest
-    # needs: docker_image_scanning
-    needs: build_and_push
+    needs: docker_image_scanning
+    # needs: build_and_push
     permissions:
       issues: write
     steps:
@@ -209,20 +209,14 @@ jobs:
           if [ "$currentSlot" == "blue" ]; then
             oldSlot="blue"
             newSlot="green"
-            deploymentOption=$newSlot.enabled=true
-            echo $deploymentOption
-            echo "oldSlot=$oldSlot" >> $GITHUB_ENV
-            echo "newSlot=$newSlot" >> $GITHUB_ENV
-            helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_green=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_green=1.${{ github.run_number }} --reuse-values
           else
             oldSlot="green"
             newSlot="blue"
-            deploymentOption=$newSlot.enabled=true
-            echo $deploymentOption
-            echo "oldSlot=$oldSlot" >> $GITHUB_ENV
-            echo "newSlot=$newSlot" >> $GITHUB_ENV
-            helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_blue=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_blue=1.${{ github.run_number }} --reuse-values
           fi
+
+          echo "oldSlot=$oldSlot" >> $GITHUB_ENV
+          echo "newSlot=$newSlot" >> $GITHUB_ENV
+          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
 
       - name: Manual aprroval
         uses: trstringer/manual-approval@v1
@@ -241,7 +235,39 @@ jobs:
         run: |
           deploymentOption=productionSlot=$newSlot
           echo $deploymentOption
-          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set $deploymentOption --reuse-values
+
+          # Deploy the new version (either blue or green) and wait for it to become ready
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.uri_env_${newSlot}=mysql-prod.prod-db --set microservice.current_environment_${newSlot}=prod --reuse-values
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} --timeout=60s; then
+            echo "Deployment failed. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
+
+          # Swap selectors to direct production traffic to the new version (newSlot)
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set "$deploymentOption" --reuse-values
+
+          # Allow some time for Kubernetes to apply the Service update
+          sleep 5
+
+          # Fetch the current selector for the production service and compare it to the desired state
+          CURRENT_SELECTOR=$(kubectl get svc "${{env.APP_NAME_SHORT}}-prod" -n ${{env.NAMESPACE}} -o=jsonpath='{.spec.selector.slot}')
+
+          if [[ "$CURRENT_SELECTOR" == *"${newSlot}"* ]]; then
+            echo "Service selector updated successfully."
+          else
+            echo "Service selector not updated. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
+
+          # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.uri_env_${oldSlot}=mysql-stage.stage-db --set microservice.current_environment_${newSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} --timeout=60s; then
+            echo "Deployment failed. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
 
       # - name: Cleanup Old slot
       #   run: |
