test

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -208,27 +208,27 @@ jobs:
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
 
-      # - name: Deploy to Staging
-      #   run: |
-      #     currentSlot=`(helm get values --all ${{env.APP_NAME_SHORT}} | grep -Po 'productionSlot: \K.*')`
-      #     echo $currentSlot
-      #     if [ "$currentSlot" == "blue" ]; then
-      #       oldSlot="blue"
-      #       newSlot="green"
-      #     else
-      #       oldSlot="green"
-      #       newSlot="blue"
-      #     fi
+      - name: Deploy to Staging
+        run: |
+          currentSlot=`(helm get values --all ${{env.APP_NAME_SHORT}} | grep -Po 'productionSlot: \K.*')`
+          echo $currentSlot
+          if [ "$currentSlot" == "blue" ]; then
+            oldSlot="blue"
+            newSlot="green"
+          else
+            oldSlot="green"
+            newSlot="blue"
+          fi
 
-      #     echo "oldSlot=$oldSlot" >> $GITHUB_ENV
-      #     echo "newSlot=$newSlot" >> $GITHUB_ENV
-      #     helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
+          echo "oldSlot=$oldSlot" >> $GITHUB_ENV
+          echo "newSlot=$newSlot" >> $GITHUB_ENV
+          # helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
 
-      #     if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-stage -n ${{env.NAMESPACE}}; then
-      #       echo "Deployment failed. Starting rollback..."
-      #       helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
-      #       exit 1
-      #     fi
+          # if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-stage -n ${{env.NAMESPACE}}; then
+          #   echo "Deployment failed. Starting rollback..."
+          #   helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+          #   exit 1
+          # fi
 
       # - name: Manual aprroval
       #   uses: trstringer/manual-approval@v1
