test

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -248,35 +248,17 @@ jobs:
           deploymentOption=productionSlot=$newSlot
           echo $deploymentOption
 
-          # Deploy the new version (either blue or green) and wait for it to become ready
-          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --reuse-values
+          # # Deploy the new version (either blue or green) and wait for it to become ready
+          # helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --reuse-values
 
-          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}}; then
-            echo "Deployment failed. Starting rollback..."
-            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
-            exit 1
-          fi
-
-          # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
-          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
-
-          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}}; then
-            echo "Deployment failed. Starting rollback..."
-            CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
-
-            # Calculate the target revision for rolling back 2 versions
-            TARGET_REVISION=$((CURRENT_REVISION - 2))
-
-            # Perform the rollback
-            helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
-            exit 1
-          fi
+          # if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}}; then
+          #   echo "Deployment failed. Starting rollback..."
+          #   helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+          #   exit 1
+          # fi
 
           # Swap selectors to direct production traffic to the new version (newSlot)
           helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set "$deploymentOption" --reuse-values
-
-          # Allow some time for Kubernetes to apply the Service update
-          sleep 5
 
           # Fetch the current selector for the production service and compare it to the desired state
           CURRENT_SELECTOR=$(kubectl get svc "${{env.APP_NAME_SHORT}}-prod" -n ${{env.NAMESPACE}} -o=jsonpath='{.spec.selector.slot}')
@@ -287,13 +269,28 @@ jobs:
             echo "Service selector not updated. Starting rollback..."
             CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
 
-            # Calculate the target revision for rolling back 3 versions
-            TARGET_REVISION=$((CURRENT_REVISION - 3))
+            # Calculate the target revision for rolling back 2 versions
+            TARGET_REVISION=$((CURRENT_REVISION - 2))
 
             # Perform the rollback
             helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
             exit 1
           fi
+
+          # # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
+          # helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+
+          # if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}}; then
+          #   echo "Deployment failed. Starting rollback..."
+          #   CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
+
+          #   # Calculate the target revision for rolling back 3 versions
+          #   TARGET_REVISION=$((CURRENT_REVISION - 3))
+
+          #   # Perform the rollback
+          #   helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
+          #   exit 1
+          # fi
 
       # - name: Cleanup Old slot
       #   run: |
