test

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -248,62 +248,54 @@ jobs:
           deploymentOption=productionSlot=$newSlot
           echo $deploymentOption
 
-            helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+          # Deploy the new version (either blue or green) and wait for it to become ready
+          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --reuse-values
 
-          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-prod -n ${{env.NAMESPACE}}; then
-            echo "Deployment failed. Starting rollback..."
-            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
-            exit 1
+          # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
+          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --reuse-values
+
+          Start rollout status checks in the background for both deployments
+          kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} &
+          PID1=$!
+
+          kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} &
+          PID2=$!
+
+          # Wait for both background processes to complete
+          wait $PID1
+          EXIT_CODE1=$?
+
+          wait $PID2
+          EXIT_CODE2=$?
+
+          # Check if any of the rollouts failed
+          if [ $EXIT_CODE1 -ne 0 ] || [ $EXIT_CODE2 -ne 0 ]; then
+              echo "Deployment failed. Starting rollback..."
+              helm rollback "${{env.APP_NAME_SHORT}}"
+              exit 1
+          else
+              echo "Both deployments successfully rolled out."
           fi
 
-          # Deploy the new version (either blue or green) and wait for it to become ready
-          # helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+          # Swap selectors to direct production traffic to the new version (newSlot)
+          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set $deploymentOption --reuse-values
 
-          # # # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
-          # # helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+          # Fetch the current selector for the production service and compare it to the desired state
+          CURRENT_SELECTOR=$(kubectl get svc "${{env.APP_NAME_SHORT}}-prod" -n ${{env.NAMESPACE}} -o=jsonpath='{.spec.selector.slot}')
 
-          # # Start rollout status checks in the background for both deployments
-          # kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} &
-          # PID1=$!
+          if [[ "$CURRENT_SELECTOR" == *"${newSlot}"* ]]; then
+            echo "Service selector updated successfully."
+          else
+            echo "Service selector not updated. Starting rollback..."
+            CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
 
-          # kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} &
-          # PID2=$!
+            # Calculate the target revision for rolling back 2 versions
+            TARGET_REVISION=$((CURRENT_REVISION - 2))
 
-          # # Wait for both background processes to complete
-          # wait $PID1
-          # EXIT_CODE1=$?
-
-          # wait $PID2
-          # EXIT_CODE2=$?
-
-          # # Check if any of the rollouts failed
-          # if [ $EXIT_CODE1 -ne 0 ] || [ $EXIT_CODE2 -ne 0 ]; then
-          #     echo "Deployment failed. Starting rollback..."
-          #     helm rollback "${{env.APP_NAME_SHORT}}"
-          #     exit 1
-          # else
-          #     echo "Both deployments successfully rolled out."
-          # fi
-
-          # # Swap selectors to direct production traffic to the new version (newSlot)
-          # helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set $deploymentOption --reuse-values
-
-          # # Fetch the current selector for the production service and compare it to the desired state
-          # CURRENT_SELECTOR=$(kubectl get svc "${{env.APP_NAME_SHORT}}-prod" -n ${{env.NAMESPACE}} -o=jsonpath='{.spec.selector.slot}')
-
-          # if [[ "$CURRENT_SELECTOR" == *"${newSlot}"* ]]; then
-          #   echo "Service selector updated successfully."
-          # else
-          #   echo "Service selector not updated. Starting rollback..."
-          #   CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
-
-          #   # Calculate the target revision for rolling back 2 versions
-          #   TARGET_REVISION=$((CURRENT_REVISION - 2))
-
-          #   # Perform the rollback
-          #   helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
-          #   exit 1
-          # fi
+            # Perform the rollback
+            helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
+            exit 1
+          fi
 
       # - name: Cleanup Old slot
       #   run: |
