added slack to pipelines, corrected resource limits etc

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -21,6 +21,7 @@ env:
   # ecr repo
   ECR_REPO_NAME: my-ecr
   NAMESPACE: spring-petclinic
+  SLACK_WEBHOOK_URL: ${{secrets.API_GATEWAY_SLACK_WEBHOOK}}
 
 jobs:
   # setup:
@@ -36,6 +37,22 @@ jobs:
   #         java-version: "11"
   #         cache: "maven"
   #         cache-dependency-path: "${{env.APP_PATH}}/pom.xml"
+
+  #     - name: Notify Slack on Failure
+  #       if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "danger",
+  #               "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
   # integration_tests:
   #   runs-on: ubuntu-latest
@@ -54,6 +71,22 @@ jobs:
 
   #     - name: Run tests
   #       run: cd ${{env.APP_PATH}} && mvn test
+
+  #     - name: Notify Slack on Failure
+  #       if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "danger",
+  #               "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
   # code_quality_and_security_scanning:
   #   runs-on: ubuntu-latest
@@ -95,6 +128,22 @@ jobs:
   #         -Dsonar.login=${{ env.SONAR_TOKEN }} \
   #         -Dsonar.qualitygate.wait=true \
   #         -Dsonar.dependencyCheck.reportPath=.${{env.APP_PATH}}/reports/dependency-check-report.html
+
+  #     - name: Notify Slack on Failure
+  #       if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "danger",
+  #               "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
   build_and_push:
     runs-on: ubuntu-latest
@@ -142,25 +191,57 @@ jobs:
           tags: ${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}}:1.${{ github.run_number }}
           push: true
 
-  # docker_image_scanning:
-  #   runs-on: ubuntu-latest
-  #   needs: build_and_push
-  #   steps:
-  #     - name: Check out repository code
-  #       uses: actions/checkout@v4
+      - name: Notify Slack on Failure
+        if: failure()
+        uses: 8398a7/action-slack@v3
+        with:
+          status: custom
+          fields: workflow,job,commit,repo,ref,author,took
+          custom_payload: |
+            {
+              "attachments": [{
+                "color": "danger",
+                "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+              }]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
-  #     - name: Configure AWS Credentials
-  #       uses: aws-actions/configure-aws-credentials@v4
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ secrets.AWS_REGION }}
+  docker_image_scanning:
+    runs-on: ubuntu-latest
+    needs: build_and_push
+    steps:
+      - name: Check out repository code
+        uses: actions/checkout@v4
 
-  #     - name: Login to Amazon ECR Private
-  #       id: login-ecr-private
-  #       uses: aws-actions/amazon-ecr-login@v2
-  #       with:
-  #         registry-type: private
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+
+      - name: Login to Amazon ECR Private
+        id: login-ecr-private
+        uses: aws-actions/amazon-ecr-login@v2
+        with:
+          registry-type: private
+
+      - name: Notify Slack on Failure
+        if: failure()
+        uses: 8398a7/action-slack@v3
+        with:
+          status: custom
+          fields: workflow,job,commit,repo,ref,author,took
+          custom_payload: |
+            {
+              "attachments": [{
+                "color": "danger",
+                "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+              }]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
   #     - name: Scan the Docker image with Trivy
   #       uses: aquasecurity/trivy-action@master
@@ -171,6 +252,22 @@ jobs:
   #         ignore-unfixed: true
   #         vuln-type: "os,library"
   #         severity: "CRITICAL,HIGH"
+
+  #     - name: Notify Slack on Failure
+  #       if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "danger",
+  #               "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
   deployment:
     runs-on: ubuntu-latest
@@ -201,12 +298,15 @@ jobs:
           chmod 700 get_helm.sh
           ./get_helm.sh
 
-      - name: Set up Kubeconfig
-        run: |
-          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
+      - name: Install Dependencies for Integration Tests
+        run: cd cypress && npm install
 
       - name: Install jq
         run: sudo apt-get update && sudo apt-get install -y jq
+
+      - name: Set up Kubeconfig
+        run: |
+          aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
 
       - name: Deploy to Staging
         run: |
@@ -224,26 +324,63 @@ jobs:
           echo "newSlot=$newSlot" >> $GITHUB_ENV
           helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
 
-          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot} -n ${{env.NAMESPACE}}; then
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot} -n ${{env.NAMESPACE}} --timeout=180s; then
             echo "Deployment failed. Starting rollback..."
             helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
             exit 1
           fi
 
-      - name: Manual aprroval
-        uses: trstringer/manual-approval@v1
+      - name: Check if all stage pods are running
+        run: |
+          set -e
+          TIMEOUT=300 # Set timeout to 5 minutes.
+          INTERVAL=10 # Check every 10 seconds.
+          end=$((SECONDS+TIMEOUT))
+          while [ $SECONDS -lt $end ]; do
+            # Get the status of pods with the env=stage label
+            POD_STATUSES=$(kubectl get pods -l env=stage -o=jsonpath='{.items[*].status.phase}')
+            
+            # Check if all pods are in the Running state
+            if [[ $(echo $POD_STATUSES | grep -c "Running") -eq $(echo $POD_STATUSES | wc -w) ]]; then
+              echo "All pods with label env=stage are running."
+              break
+            else
+              echo "Waiting for all pods with label env=stage to be in Running state..."
+            fi
+            
+            # Exit loop if timeout is reached
+            if [ $SECONDS -ge $end ]; then
+              echo "Timeout reached. Not all pods are in Running state."
+              exit 1
+            fi
+            
+            sleep $INTERVAL
+          done
+
+      # - name: Manual aprroval
+      #   uses: trstringer/manual-approval@v1
+      #   with:
+      #     secret: ${{ github.TOKEN }}
+      #     approvers: Jaro233
+      #     minimum-approvals: 1
+      #     issue-title: "Deploying ${{env.APP_NAME_SHORT}} v1.${{ github.run_number }} to prod from staging"
+      #     issue-body: "Please approve or deny the deployment of version v1.${{ github.run_number }}"
+      #     exclude-workflow-initiator-as-approver: false
+      #     additional-approved-words: ""
+      #     additional-denied-words: ""
+
+      - name: Run Integration Tests
+        uses: cypress-io/github-action@v6
         with:
-          secret: ${{ github.TOKEN }}
-          approvers: Jaro233
-          minimum-approvals: 1
-          issue-title: "Deploying ${{env.APP_NAME_SHORT}} v1.${{ github.run_number }} to prod from staging"
-          issue-body: "Please approve or deny the deployment of version v1.${{ github.run_number }}"
-          exclude-workflow-initiator-as-approver: false
-          additional-approved-words: ""
-          additional-denied-words: ""
+          wait-on-timeout: 10
+          config: video=false
+          browser: chrome
+          working-directory: cypress
+        env:
+          CYPRESS_BASE_URL: "https://stage.devopshub.org"
 
       - name: Swap Production to New Version
-        # if: success() # Only proceed if tests pass
+        if: success() # Only proceed if tests pass
         run: |
           deploymentOption=productionSlot=$newSlot
           echo $deploymentOption
@@ -251,7 +388,7 @@ jobs:
           # Deploy the new version (either blue or green) and wait for it to become ready
           helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
 
-          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot} -n ${{env.NAMESPACE}}; then
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot} -n ${{env.NAMESPACE}} --timeout=180s; then
             echo "Deployment failed. Starting rollback..."
             helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
             exit 1
@@ -280,7 +417,7 @@ jobs:
           # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
           helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
 
-          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot} -n ${{env.NAMESPACE}}; then
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot} -n ${{env.NAMESPACE}} --timeout=180s; then
             echo "Deployment failed. Starting rollback..."
             CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
 
@@ -291,6 +428,22 @@ jobs:
             helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
             exit 1
           fi
+
+      - name: Notify Slack on Failure
+        if: failure()
+        uses: 8398a7/action-slack@v3
+        with:
+          status: custom
+          fields: workflow,job,commit,repo,ref,author,took
+          custom_payload: |
+            {
+              "attachments": [{
+                "color": "danger",
+                "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+              }]
+            }
+        env:
+          SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
 
       # - name: Cleanup Old slot
       #   run: |
@@ -311,6 +464,22 @@ jobs:
   #         target: "https://prod.devopshub.org"
   #         allow_issue_writing: false
 
+  #     - name: Notify Slack on Failure
+  #       if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "danger",
+  #               "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
+
   # cypress-run:
   #   runs-on: ubuntu-latest
   #   needs: zap-scan
@@ -328,3 +497,35 @@ jobs:
   #         config: video=false
   #         browser: chrome
   #         working-directory: cypress
+
+  #     - name: Notify Slack on Failure
+  #       if: failure()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "danger",
+  #               "text": "Job for ${{ env.APP_NAME_SHORT }} failed :x:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
+
+  #     - name: Notify Slack on Success
+  #       if: success()
+  #       uses: 8398a7/action-slack@v3
+  #       with:
+  #         status: custom
+  #         fields: workflow,job,commit,repo,ref,author,took
+  #         custom_payload: |
+  #           {
+  #             "attachments": [{
+  #               "color": "good",
+  #               "text": "Pipeline for ${{ env.APP_NAME_SHORT }} succeeded :white_check_mark:"
+  #             }]
+  #           }
+  #       env:
+  #         SLACK_WEBHOOK_URL: ${{ env.SLACK_WEBHOOK_URL }}
