fixed bug in blue green deployment

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -205,6 +205,9 @@ jobs:
         run: |
           aws eks update-kubeconfig --name ${{ secrets.CLUSTER_NAME }}
 
+      - name: Install jq
+        run: sudo apt-get update && sudo apt-get install -y jq
+
       - name: Deploy to Staging
         run: |
           currentSlot=`(helm get values --all ${{env.APP_NAME_SHORT}} | grep -Po 'productionSlot: \K.*')`
@@ -220,6 +223,12 @@ jobs:
           echo "oldSlot=$oldSlot" >> $GITHUB_ENV
           echo "newSlot=$newSlot" >> $GITHUB_ENV
           helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
+
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-stage -n ${{env.NAMESPACE}} --timeout=60s; then
+            echo "Deployment failed. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
+          fi
 
       - name: Manual aprroval
         uses: trstringer/manual-approval@v1
@@ -241,6 +250,7 @@ jobs:
 
           # Deploy the new version (either blue or green) and wait for it to become ready
           helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --reuse-values
+
           if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} --timeout=60s; then
             echo "Deployment failed. Starting rollback..."
             helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
@@ -260,15 +270,28 @@ jobs:
             echo "Service selector updated successfully."
           else
             echo "Service selector not updated. Starting rollback..."
-            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
+
+            # Calculate the target revision for rolling back 2 versions
+            TARGET_REVISION=$((CURRENT_REVISION - 2))
+
+            # Perform the rollback
+            helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
             exit 1
           fi
 
           # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
-          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${newSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+          helm upgrade "${{env.APP_NAME_SHORT}}" ./kubernetes/helm/app/"${{env.APP_NAME_SHORT}}" --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+
           if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} --timeout=60s; then
             echo "Deployment failed. Starting rollback..."
-            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            CURRENT_REVISION=$(helm history ${{env.APP_NAME_SHORT}} --max 1 --output json | jq '.[0].revision')
+
+            # Calculate the target revision for rolling back 3 versions
+            TARGET_REVISION=$((CURRENT_REVISION - 3))
+
+            # Perform the rollback
+            helm rollback "${{env.APP_NAME_SHORT}}" $TARGET_REVISION
             exit 1
           fi
 
