test

diff --git a/.github/workflows/api-gateway-ci-cd.yaml b/.github/workflows/api-gateway-ci-cd.yaml
--- a/.github/workflows/api-gateway-ci-cd.yaml
+++ b/.github/workflows/api-gateway-ci-cd.yaml
@@ -249,33 +249,39 @@ jobs:
           echo $deploymentOption
 
           # Deploy the new version (either blue or green) and wait for it to become ready
-          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod 
+          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${newSlot}=kubernetes --set microservice.current_environment_${newSlot}=prod --set microservice.image.repository_${newSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${newSlot}=1.${{ github.run_number }} --reuse-values
 
-          # # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
-          helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
-
-          # Start rollout status checks in the background for both deployments
-          kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} &
-          PID1=$!
-
-          kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} &
-          PID2=$!
-
-          # Wait for both background processes to complete
-          wait $PID1
-          EXIT_CODE1=$?
-
-          wait $PID2
-          EXIT_CODE2=$?
-
-          # Check if any of the rollouts failed
-          if [ $EXIT_CODE1 -ne 0 ] || [ $EXIT_CODE2 -ne 0 ]; then
-              echo "Deployment failed. Starting rollback..."
-              helm rollback "${{env.APP_NAME_SHORT}}"
-              exit 1
-          else
-              echo "Both deployments successfully rolled out."
+          if ! kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-stage -n ${{env.NAMESPACE}}; then
+            echo "Deployment failed. Starting rollback..."
+            helm rollback "${{env.APP_NAME_SHORT}}"  # This rolls back to the previous revision
+            exit 1
           fi
+
+          # Update the old version (oldSlot) to the stage configuration and with new app version, next wait for it to become ready
+          # helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set microservice.profile_env_${oldSlot}=kubernetes-stage --set microservice.current_environment_${oldSlot}=stage --set microservice.image.repository_${oldSlot}=${{ steps.login-ecr-private.outputs.registry }}/${{env.ECR_REPO_NAME}} --set microservice.image.tag_${oldSlot}=1.${{ github.run_number }} --reuse-values
+
+          # # Start rollout status checks in the background for both deployments
+          # kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${newSlot}-prod -n ${{env.NAMESPACE}} &
+          # PID1=$!
+
+          # kubectl rollout status deployment/${{env.APP_NAME_SHORT}}-${oldSlot}-stage -n ${{env.NAMESPACE}} &
+          # PID2=$!
+
+          # # Wait for both background processes to complete
+          # wait $PID1
+          # EXIT_CODE1=$?
+
+          # wait $PID2
+          # EXIT_CODE2=$?
+
+          # # Check if any of the rollouts failed
+          # if [ $EXIT_CODE1 -ne 0 ] || [ $EXIT_CODE2 -ne 0 ]; then
+          #     echo "Deployment failed. Starting rollback..."
+          #     helm rollback "${{env.APP_NAME_SHORT}}"
+          #     exit 1
+          # else
+          #     echo "Both deployments successfully rolled out."
+          # fi
 
           # Swap selectors to direct production traffic to the new version (newSlot)
           helm upgrade ${{env.APP_NAME_SHORT}} ./kubernetes/helm/app/${{env.APP_NAME_SHORT}} --set $deploymentOption --reuse-values
